 --all credits to lu_zi#0192 for the translations Thank You
lang.set_translate('zh')

local f = lang.find
local t = lang.translate

t(f('Kosatka not found'), '未找到虎鲸')
t(f('Terrorbyte not found'), '未找到恐霸')
t(f('No Special Cargo Found'), '未找到特殊货物')
t(f('No Vehicle Cargo Found'), '未找到载具货物')
t(f('No PC Found'), '未找到电脑')
t(f('TP to MC Product'), '传送到摩托帮货物')
t(f('TP to Heli'), '传送到直升机')
t(f('TP to Boat'), '传送到船')
t(f('TP to Plane'), '传送到飞机')
t(f('No MC Product Found'), '未找到摩托帮货物')
t(f('TP to Supplies'), '传送到补给品')
t(f('TP to Dune'), '传送到沙丘FAV')
t(f('TP to Flatbed'), '传送到平板拖车')
t(f('No Bunker Supplies Found'), '未找到地堡补给品')
t(f('No Payhone Found'), '未找到公共电话亭')
t(f('Dock Not Found'), '未找到出口码头')
t(f('Charger will not Spawn in interior'), '不要在室内生成道奇战马')
t(f('Fuck that car'), '去他妈的上一辆车,已为您更换新的')
t(f('Charger Spawned'), '道奇战马已生成')
t(f('Player has left Charger and it has been deleted'), '玩家已离开道奇战马并已被删除')
t(f('You made them rage quit'), '你让他们怒不可遏')
t(f('Improper Vehicle Name (check the spelling)'), '载具名称不正确(请检查你的拼写)')
t(f('No Ped Cage Found'), '未找到Ped笼子')
t(f('No Obj Cage Found'), '未找到物体笼子')
t(f('Magnet Intensity'), '电磁脉冲样式')
t(f('Changes Magnet to Push Away or Blow up'), '更改电磁脉冲样式为推开或炸毁')
t(f(' Caged'), ' 已被笼子困住')
t(f(' Broke Free'), ' 挣脱了笼子')
t(f(' has been smashed'), ' 被粉碎了')
t(f(' has been run over'), ' 被碾过了')
t(f('Could not reach '), '无法攻击 ')
t(f('Teleports'), '传送')
t(f('TP into Avenger'), '传送到复仇者')
t(f('Teleport into Avengers holding area/facility'), '传送到设施')
t(f('TP into Kosatka'), '传送到虎鲸')
t(f('MUST HAVE CALLED IN Teleport to Kosatka Cayo Perico Heist board'), '传送到佩里科岛抢劫面板')
t(f('TP into MOC'), '传送到机动作战中心')
t(f('Teleport into MOC command center/bunker'), '传送到地堡')
t(f('TP into Terrorbyte'), '传送到恐霸')
t(f('Teleport to Terrorbyte Business control'), '传送到夜总会')
t(f('TP to Special Cargo'), '传送到特殊货物')
t(f('Teleport to Special Cargo pickup'), '传送并拾取特殊货物')
t(f('TP to Vehicle Cargo'), '传送到载具货物')
t(f('Teleport to Vehicle Cargo pickup'), '传送并拾取载具货物')
t(f('TP to PC'), '传送到电脑')
t(f('Teleport to PC at the Desk'), '传送到办公桌上的电脑')
t(f('Teleport to MC Club Product Pickup/Sale'), '传送并拾取摩托帮货物')
t(f('TP to Bunker Supplies/Sale'), '传送到地堡货物')
t(f('Teleport to Bunker Supplies/Sale Pickup'), '传送并拾取地堡货物')
t(f('TP to Payphone'), '传送到公共电话亭')
t(f('Teleport to Payphone (must have called Franklin already)'), '传送到公共电话亭(必须已经打电话给富兰克林请求暗杀差事)')
t(f('TP to Exotic Export Dock'), '传送到出口码头')
t(f('Teleport to Exotic Export Dock'), '传送到出口码头')
t(f('Spawn FF9 EMP Charger'), '生成速度与激情9的电磁脉冲道奇战马')
t(f('Spawn Charger from FF9 with Electro Magnet capabilities'), '生成带有电磁脉冲功能的道奇战马')
t(f('AcjokerScript'), 'Acjoker脚本')
t(f('Cages'), '困住玩家')
t(f('Vehicular Assault'), '载具攻击')
t(f('Will Smash or Run the Player over every time they try and stand up'), '使玩家无法站起来')
t(f('Invisible Vehicles'), '隐形载具')
t(f('Change the assault vehicles to invisible'), '将攻击载具更改为不可见')
t(f('Change Vehicle used for Vehicular Assault'), '更改为用于载具攻击的载具')
t(f('Vehicle List'), '载具列表')
t(f('Changes Vehicles used for Vehicular Assault'), '更改为用于载具攻击的载具')
t(f('Assault Rate'), '攻击频率')
t(f('Adjust rate at which vehicles attack'), '调整载具攻击频率')
t(f('Enter Custom Vehicle Hash'), '输入自定义载具模型名')
t(f('Enter Vehicle Hash to change Vehicular Assault Vehicle'), '输入车辆模型名以更改载具为攻击载具')
t(f('Ped Cage'), 'Ped笼子')
t(f('Traps Player in a Cage of Peds'), '将玩家困在Ped笼子里')
t(f('Change Ped for Cage'), '更改Ped笼子样式')
t(f('Will Change the Ped if they move or if you delete current ped'), '如果他们移动或删除当前Ped,请更改Ped样式')
t(f('Free from Ped Cage'), '解除Ped笼子')
t(f('Free Player from Ped Cage'), '将玩家从Ped笼子中释放')
t(f('Object Cage'), '物体笼子')
t(f('Traps Player in a Cage of Objects'), '将玩家困在物体笼子里')
t(f('Change Object for Cage'), '更改物体笼子样式')
t(f('Will Change the Object if they move or if you delete current object'), '如果他们移动或删除当前物体,请更改物体样式')
t(f('Free from Object Cage'), '解除物体笼子')
t(f('Free Player from Object Cage'), '将玩家从物体笼子中释放')
t(f('Ambient Female NPCs'), '游戏中的女性NPC')
t(f('Changes Peds to Ambient Females'), '更改Ped样式为游戏中的女性NPC')
t(f('Ambient Male NPCs'), '游戏中的男性NPC')
t(f('Changes Peds to Ambient Males'), '更改Ped样式为游戏中的男性NPC')
t(f('Cutscene Peds'), '过场动画NPC')
t(f('Changes Peds to Cutscene Peds(dont usually speak)'), '更改Ped样式为游戏中的过场动画NPC(非必要不使用)')
t(f('Gang Members'), '帮派成员')
t(f('Changes Peds to Gang Members'), '更改Ped样式为游戏中的帮派成员')
t(f('Multiplayer Peds'), '在线模式中的NPC')
t(f('Changes Peds to Multiplayer Peds'), '更改Ped样式为在线模式中的NPC')
t(f('Multiplayer Scenario Females'), '在线模式过场动画中的女性NPC')
t(f('Changes Peds to Multiplayer Scenario Females'), '更改Ped样式为在线模式过场动画中的女性NPC')
t(f('Multiplayer Scenario Males'), '在线模式过场动画中的男性NPC')
t(f('Changes Peds to Multiplayer Scenario Males'), '更改Ped样式为在线模式过场动画中的男性NPC')
t(f('Story Mode Characters'), '故事模式角色')
t(f('Changes Peds to Story Mode Characters'), '更改Ped样式为故事模式角色')
t(f('Story Scenario Females'), '故事模式过场动画女性NPC')
t(f('Changes Peds to Story Scenario Females'), '更改Ped样式为故事模式过场动画女性NPC')
t(f('Story Scenario Males'), '故事模式过场动画男性NPC')
t(f('Changes Peds to Story Scenario Males'), '更改Ped样式为故事模式过场动画男性NPC')
t(f('DLC Peds'), 'DLC中的NPC')
t(f('Changes Peds to Peds from the DLCs'), '更改Ped样式为DLC中的NPC')
t(f('Street Signs'), '路牌')
t(f('Changes Objects to Street Signs'), '更改物体样式为路牌')
t(f('Doors'), '门')
t(f('Changes Objects to Doors'), '更改物体样式为门')
t(f('Changes Objects to Interior Props'), '更改物体样式为室内道具')
t(f('Exterior'), '外部道具')
t(f('Changes Objects to Exterior Props'), '更改物体样式为外部道具')
t(f('Juggle Player with Vehicles'), '开始击飞')
t(f('Juggles Player by hitting them upwards repeatedly'), '反复击飞玩家')
t(f('Change the Juggle vehicles to invisible'), '将击飞载具更改为不可见')
t(f('Change Vehicle used for Juggling'), '更改用于击飞的载具')
t(f('Changes Vehicles used for Juggling'), '更改用于击飞的载具')
t(f('Juggle Rate'), '击飞频率')
t(f('Adjust rate at which vehicles shoot upwards'), '更改载具击飞间隔速度')
t(f('Enter Vehicle Hash to change Juggle Vehicle'), '输入车辆模型名以更改击飞车辆')
t(f('Juggle Player'), '击飞玩家')
t(f(' is being juggled'), ' 正在被击飞')
t(f('Blow Up'), '爆炸')
t(f('Push Away or Blow up'), '爆炸 或 推开按')
t(f('Make it Rain '), '在玩家身上下雨 ')
t(f('Explode Player Loop '), '循环爆炸类型 ')
t(f('Make it Rain'), '在玩家身上下雨')
t(f('Explode Player'), '爆炸玩家')
t(f('The Full Monty'), '混合恶搞')
t(f('Activate ped cage, object cage, and explode loop at the same time'), '同时启用Ped笼子,物体笼子,循环爆炸来恶搞玩家')
t(f('Make it Rain : Snowballs'), '类型:雪球')
t(f('Make it Rain your choice of weapon in all directions'), '启用下雨')
t(f('Weapon Choices'), '类型')
t(f('Changes the weapon that rains down on them'), '更改在玩家身上下雨的类型')
t(f('Weapon Speed'), '下雨速度')
t(f('Adjust the speed of the Weapons'), '更改下雨的速度')
t(f('Katy Perry'), '发射烟花')
t(f('Turn them into a Firework by hitting them up in the air with Juggle and activating Make it Rain Fireworks'), '弹飞玩家并把玩家变成烟花炸飞')
t(f('Explode Player Loop : Grenade'), '类型:手榴弹')
t(f('Explode Player in a continous loop'), '循环爆炸玩家')
t(f('Change Explosion Type'), '更改爆炸类型')
t(f('Changes Explosion used for exploding the player'), '更改爆炸玩家的类型')
t(f('Explosion Damage Scale'), '更改爆炸大小')
t(f('Adjust the Damage Scale of the Explosions'), '更改爆炸玩家的大小')
t(f('Invisible Explosions'), '隐形爆炸')
t(f('Change the Explosions to invisible'), '让玩家看不见爆炸')
t(f('Inaudible Explosions'), '无声爆炸')
t(f('Change the Explosions so that you can no longer hear them'), '让玩家听不见爆炸')
t(f('Explosion Shake'), '晃动视角数值')
t(f('Adjust the Camera Shake caused by the Explosions'), '调整由爆炸引起的视角晃动数值')
t(f('Damage Off'), '无伤爆炸')
t(f('Change the Explosions to not cause Damage'), '让玩家受不到爆炸伤害')
t(f('Explosion Delay'), '延迟')
t(f('Adjust the Delay in between Explosions'), '调成距离上一次爆炸的延迟')
t(f('Alerts Off'), '关闭提示')
t(f('Turn off the alerts you get from AcjokerScript'), '关闭Acjoker脚本的提示')
t(f('Join the Discord'), '加入官方Discord')
t(f('Join the AcjokerScript Discord if you have any problems, want to suggest features, or want to help with translations'), '如果您有任何问题、想提供对脚本功能或翻译的建议,请点击此选项进入Acjoker脚本官方Discord')
t(f(': Snowballs'), '雪球')