 -- Full credits to - THEKING -#8311 for the translations Thank You
lang.set_translate('de')

local f = lang.find
local t = lang.translate

t(f('Kosatka not found'), 'Kosatka wurde nicht gefunden')
t(f('Terrorbyte not found'), 'Terrorbyte wurde nicht gefunden')
t(f('No Special Cargo Found'), 'Spezialfracht wurde nicht gefunden')
t(f('No Vehicle Cargo Found'), 'Fahrzeugfracht wurde nicht gefunden')
t(f('No PC Found'), 'PC wurde nicht gefunden')
t(f('TP to MC Product'), 'TP zu MC Produkten')
t(f('TP to Heli'), 'TP zum Heli')
t(f('TP to Boat'), 'TP zum Boot')
t(f('TP to Plane'), 'TP zum Flugzeug')
t(f('No MC Product Found'), 'Keine MC Produkte gefunden')
t(f('TP to Supplies'), 'TP zum Nachschub')
t(f('TP to Dune'), 'TP zum Dune')
t(f('TP to Flatbed'), 'TP zum Tieflader')
t(f('No Bunker Supplies Found'), 'Kein Bunker Nachschub gefunden')
t(f('No Payhone Found'), 'Kein Telefon gefunden')
t(f('Dock Not Found'), 'Kein Dock gefunden')
t(f('Charger will not Spawn in interior'), 'Der Charger spawnt nicht in Innenräumen')
t(f('Fuck that car'), 'Fic*e das Auto')
t(f('Charger Spawned'), 'Charger gespawned')
t(f('Player has left Charger and it has been deleted'), 'Der Spieler hat den Charger verlassen, er wurde gelöscht')
t(f('You made them rage quit'), 'Du hast ihhn zum verlassen gebracht')
t(f('Improper Vehicle Name (check the spelling)'), 'Ungültiger Fahrzeugname (überprüfe die Schreibweise)')
t(f('No Ped Cage Found'), 'Kein PED - Käfig gefunden')
t(f('No Obj Cage Found'), 'Kein OBJ - Käfig gefunden')
t(f('Magnet Intensity'), 'Magnet Anziehungskraft')
t(f('Changes Magnet to Push Away or Blow up'), 'Ändert den Magneten zu wegschieben oder sprengen')
t(f(' Caged'), ' eingesperrt')
t(f(' Broke Free'), ' entkommen')
t(f(' has been smashed'), ' wurde zertrümmert')
t(f(' has been run over'), ' wurde umgefahren')
t(f('Could not reach '), 'Konnte nicht erreichen: ')
t(f('Teleports'), 'Teleports')
t(f('TP into Avenger'), 'TP in die Avanger')
t(f('Teleport into Avengers holding area/facility'), 'TP in die Basis')
t(f('TP into Kosatka'), 'TP in die Kosatka')
t(f('MUST HAVE CALLED IN Teleport to Kosatka Cayo Perico Heist board'), 'MUSS ANRUFEN HABEN Teleport zum Kosatka Cayo Perico Heist Board')
t(f('TP into MOC'), 'TP in die MOC')
t(f('Teleport into MOC command center/bunker'), 'TP in den Bunker')
t(f('TP into Terrorbyte'), 'TP in den Terrorbyte')
t(f('Teleport to Terrorbyte Business control'), 'TP zur Terrorbyte Geschäftverwaltung')
t(f('TP to Special Cargo'), 'TP zur Spezialfracht')
t(f('Teleport to Special Cargo pickup'), 'TP zur Spezialfracht abholung')
t(f('TP to Vehicle Cargo'), 'TP zur Fahrzeugfracht')
t(f('Teleport to Vehicle Cargo pickup'), 'TP zur Fahrzeugfracht abholung')
t(f('TP to PC'), 'TP zum PC')
t(f('Teleport to PC at the Desk'), 'TP zum PC am Schreibtisch')
t(f('Teleport to MC Club Product Pickup/Sale'), 'TP zu MC Club Produktabholung/Produktverkauf')
t(f('TP to Bunker Supplies/Sale'), 'TP zu Bunker Nachschub/Verkauf')
t(f('Teleport to Bunker Supplies/Sale Pickup'), 'TP zu Bunker Nachschub/Verkaufsabholung')
t(f('TP to Payphone'), 'TP zum Auftrags-Telefon')
t(f('Teleport to Payphone (must have called Franklin already)'), 'TP zum Auftrags-Telefon (musst vorher Franklin anrufen)')
t(f('TP to Exotic Export Dock'), 'TP zum Exotic Export Dock')
t(f('Teleport to Exotic Export Dock'), 'TP zum Exotic Export Dock')
t(f('Spawn FF9 EMP Charger'), 'FF9 EMP Charger spawnen')
t(f('Spawn Charger from FF9 with Electro Magnet capabilities'), 'Spawnt Charger von FF9 mit Elektromagnet-Fähigkeiten')
t(f('AcjokerScript'), 'AcjokerScript')
t(f('Cages'), 'Käfige')
t(f('Vehicular Assault'), 'Fahrzeugangriff')
t(f('Will Smash or Run the Player over every time they try and stand up'), 'Wird den Spieler jedes Mal zerschmettern oder überfahren, wenn er versucht aufzustehen')
t(f('Invisible Vehicles'), 'Unsichtbare Fahrzeuge')
t(f('Change the assault vehicles to invisible'), 'Macht die Angriffsfahrzeuge unsichtbar')
t(f('Change Vehicle used for Vehicular Assault'), 'Ändern Sie das Fahrzeug, welches für den Angriff verwendet wird')
t(f('Vehicle List'), 'Fahrzeug-Liste')
t(f('Changes Vehicles used for Vehicular Assault'), 'Ändert Fahrzeuge, die für den Angriff verwendet werden')
t(f('Assault Rate'), 'Angriffsrate')
t(f('Adjust rate at which vehicles attack'), 'Passe die Rate an, mit der Fahrzeuge angreifen')
t(f('Enter Custom Vehicle Hash'), 'eigenen Fahrzeug-Hash eingeben')
t(f('Enter Vehicle Hash to change Vehicular Assault Vehicle'), 'gib eine Fahrzeug-Hash ein, um das Angreiferfahrzeug zu ändern')
t(f('Ped Cage'), 'Ped Käfig')
t(f('Traps Player in a Cage of Peds'), 'Fängt den Spieler in einem Ped-Käfig ein')
t(f('Change Ped for Cage'), 'Ändere das Ped für den Käfig')
t(f('Will Change the Ped if they move or if you delete current ped'), 'Ändert das Ped wenn es sich bewegt oder du das aktuelle Ped löschst')
t(f('Free from Ped Cage'), 'Vom Ped-Käfig befreien')
t(f('Free Player from Ped Cage'), 'Befreit den Spieler aus dem Ped-Käfig')
t(f('Object Cage'), 'Objekt-Käfig')
t(f('Traps Player in a Cage of Objects'), 'Fängt den Spieler in einem Objekt-Käfig ein')
t(f('Change Object for Cage'), 'Ändere das Objekt für den Käfig')
t(f('Will Change the Object if they move or if you delete current object'), 'Ändert das Objekt wenn es sich bewegt oder du das aktuelle Objekt löschst')
t(f('Free from Object Cage'), 'Vom Objekt-Käfig befreien')
t(f('Free Player from Object Cage'), 'Befreit den Spieler aus dem Objekt-Käfig')
t(f('Ambient Female NPCs'), 'Umgebungs-Fraunen NPCs')
t(f('Changes Peds to Ambient Females'), 'Ändert das Ped zu NPC Frauen aus der Umgebung')
t(f('Ambient Male NPCs'), 'Umgebungs-Männer NPCs')
t(f('Changes Peds to Ambient Males'), 'Ändert das Ped zu NPC Männern aus der Umgebung')
t(f('Cutscene Peds'), 'Zwischensequenz-Produkten')
t(f('Changes Peds to Cutscene Peds(dont usually speak)'), 'Ändert das Ped zu Zwischensequenz-Peds')
t(f('Gang Members'), 'Gang Mitglieder')
t(f('Changes Peds to Gang Members'), 'Ändert das Ped zu Gang Mitgliedern')
t(f('Multiplayer Peds'), 'Mehrspieler Peds')
t(f('Changes Peds to Multiplayer Peds'), 'Ändert das Ped zu Mehrspieler Peds')
t(f('Multiplayer Scenario Females'), 'Mehrspieler-Szenario Frauen Peds')
t(f('Changes Peds to Multiplayer Scenario Females'), 'Ändert das Ped zu Mehrspieler-Szenario Fauen Peds')
t(f('Multiplayer Scenario Males'), 'Mehrspieler-Szenario Männer Peds')
t(f('Changes Peds to Multiplayer Scenario Males'), 'Ändert das Ped zu Mehrspieler-Szenario Männer Peds')
t(f('Story Mode Characters'), 'Story Mode Charactere')
t(f('Changes Peds to Story Mode Characters'), 'Ändert das Ped zu Story Mode Charactere')
t(f('Story Scenario Females'), 'Story-Szenario Frauen')
t(f('Changes Peds to Story Scenario Females'), 'Ändert das Ped zu Story-Szenario Frauen')
t(f('Story Scenario Males'), 'Story-Szenario Männer')
t(f('Changes Peds to Story Scenario Males'), 'Ändert das Ped zu Story-Szenario Männer')
t(f('DLC Peds'), 'DLC Peds')
t(f('Changes Peds to Peds from the DLCs'), 'Ändert das Ped zu DLC Peds')
t(f('Street Signs'), 'Strassenschilder')
t(f('Changes Objects to Street Signs'), 'Ändert das Objekt zu Strassenschilder')
t(f('Doors'), 'Türen')
t(f('Changes Objects to Doors'), 'Ändert das Objekt zu Türen')
t(f('Changes Objects to Interior Props'), 'Ändert das Objekt zu Inneneinrichtungsrequisiten')
t(f('Exterior'), 'Aussen')
t(f('Changes Objects to Exterior Props'), 'Ändert das Objekt zu Außeninrichtungsrequisiten')
t(f('Juggle Player with Vehicles'), 'Jongliere Spieler mit Fahrzeugen')
t(f('Juggles Player by hitting them upwards repeatedly'), 'Jongliert den Spieler, indem er wiederholt nach oben geschlgen wird')
t(f('Change the Juggle vehicles to invisible'), 'Macht die Jongleur-Fahrzeuge unsichtbar')
t(f('Change Vehicle used for Juggling'), 'Fahrzeug zum Jonglieren wechseln')
t(f('Changes Vehicles used for Juggling'), 'Ändert die Fahrzeuge die fürs Jonglieren verwendet werden')
t(f('Juggle Rate'), 'Jonglier-Rate')
t(f('Adjust rate at which vehicles shoot upwards'), 'Passe die Geschwindigkeit an, mit der die Fahrzeuge Spieler nach oben schießen')
t(f('Enter Vehicle Hash to change Juggle Vehicle'), 'Fahrzeug-Hash eingeben, um Jonglier-Fahrzeug zu ändern')
t(f('Juggle Player'), 'Spieler Jonglieren')
t(f(' is being juggled'), ' wird bereits jongliert')
t(f('Make it Rain '), 'Lass es regnen')
t(f('Explode Player Loop '), 'Spieler explodieren loop')
t(f('Make it Rain'), 'Lass es regnen')
t(f('Explode Player'), 'Spieler explodieren loop')
t(f('The Full Monty'), 'The Full Monty')
t(f('Activate ped cage, object cage, and explode loop at the same time'), 'Aktiviert den Ped- und Objektkäfig sowie den Explosions-loop zur selben Zeit')
t(f('Make it Rain : Snowballs'), 'Lass es regnen: Schneebälle')
t(f('Make it Rain your choice of weapon in all directions'), 'Lasse Waffen deiner Wahl in alle richtungen regnen')
t(f('Weapon Choices'), 'Waffenauswahl')
t(f('Changes the weapon that rains down on them'), 'Ändert die Waffe die auf sie herabregnet')
t(f('Weapon Speed'), 'Waffengeschwindigkeit')
t(f('Adjust the speed of the Weapons'), 'Ändert die Geschwindigkeit der Waffen')
t(f('Katy Perry'), 'Katy Perry')
t(f('Turn them into a Firework by hitting them up in the air with Juggle and activating Make it Rain Fireworks'), 'Verwandlt sie in ein Feuerwerk indem sie in die Luft geschleudert werden und es Feuerwerke regnen lässt')
t(f('Explode Player Loop : Grenade'), 'Spieler explodieren loop: Granate')
t(f('Explode Player in a continous loop'), 'Spieler explodieren endlosschleife')
t(f('Change Explosion Type'), 'Ändert den Explosionstyp')
t(f('Changes Explosion used for exploding the player'), 'Ändert die Explosion die für die Spielerexplosion genutzt wird')
t(f('Explosion Damage Scale'), 'Explosionsschaden-Skala')
t(f('Adjust the Damage Scale of the Explosions'), 'Passe die Schadensskala der Explosionen an')
t(f('Invisible Explosions'), 'Unsichtbare Explosion')
t(f('Change the Explosions to invisible'), 'Macht die Explosionen unsichtbar')
t(f('Inaudible Explosions'), 'Geräuschlose Explosion')
t(f('Change the Explosions so that you can no longer hear them'), 'Macht die Explosionen Lautlos, so dass du sie nicht mehr hörst')
t(f('Explosion Shake'), 'Explosionserschütterung')
t(f('Adjust the Camera Shake caused by the Explosions'), 'Passe das durch die Explosionen verursachte Kamerawackeln an')
t(f('Damage Off'), 'Schaden aus')
t(f('Change the Explosions to not cause Damage'), 'Die Explosion macht keinen Schaden mehr')
t(f('Explosion Delay'), 'Explosions Verzögerung')
t(f('Adjust the Delay in between Explosions'), 'Passe die Zeit zwischen den Explosion an')
t(f('Alerts Off'), 'Warnungen aus')
t(f('Turn off the alerts you get from AcjokerScript'), 'Schaltet die Warnungen aus, die du vom AcjokerScript bekommst')
t(f('Join the Discord'), 'Tritt dem Discord bei')
t(f('Join the AcjokerScript Discord if you have any problems, want to suggest features, or want to help with translations'), 'Tritt dem AcjokerScript Discord bei, fals du Probleme hast, Funktionen vorschlagen oder bei Übersetzungen helfen möchtes')
t(f('Blow Up'), 'Sprengen')
t(f('Push Away or Blow up'), 'Wegdrücken oder Sprengen')
t(f(': Snowballs'), ': Schneebälle')